---
title: "Chapter 2 - Scale effects on land surface geometry and environmental correlation"
author: "Stephen Roecker"
date: "November 5, 2018"
output: 
  html_document: 
    number_sections: yes
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: no
editor_options: 
  chunk_output_type: console
---

```{r options}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

```{r packages}
library(ggplot2)
library(dplyr)
```

# Case Study 1 - Systematic effects of varying grid and neighorhood size on LSP

## Tidy Old Data

```{r munge, eval = FALSE}
load(file = "C:/workspace2/github/thesis_wvu/trunk/scale/lidar_data.RData")

lidar <- rbind(
  # Gilmer
  stack(gil01m.df),
  stack(gil03m.df),
  stack(gil09m.df),
  stack(gil27m.df),
  # Jefferson
  stack(jef01m.df),
  stack(jef03m.df),
  stack(jef09m.df),
  stack(jef27m.df)
  )
lidar <- within(lidar, {
  loc = ifelse(grepl("gil", ind), "Gilmer", "Jefferson")
  
  res = NA
  res[grepl("01m", ind)] = 1
  res[grepl("03m", ind)] = 3
  res[grepl("09m", ind)] = 9
  res[grepl("27m", ind)] = 27
  
  var = NA
  var[grepl("sgp", ind)] = "slope"
  var[grepl("sa", ind)]  = "aspect"
  var[grepl("kp", ind)]  = "cupro"
  var[grepl("kt", ind)]  = "cutan"
  
  ws = NA
  ws[grepl("3w", ind)]   = 3
  ws[grepl("5w", ind)]   = 5
  ws[grepl("7w", ind)]   = 7
  ws[grepl("9w", ind)]   = 9
  ws[grepl("15w", ind)]  = 15
  ws[grepl("21w", ind)]  = 21
  ws[grepl("27w", ind)]  = 27
  ws[grepl("45w", ind)]  = 45
  ws[grepl("63w", ind)]  = 63
  
  ns  = as.factor(res * ws)
  res = as.factor(res)
  ws  = as.factor(ws)
  })

lidar <- lidar[c("loc", "res", "ns", "ws", "var", "values")]

save(lidar, file = "lidar_data2.RData")

```


## Create Boxplots

```{r boxplots}

load(file = "lidar_data2.RData")

# slope boxplots
filter(lidar, var == "slope" & loc == "Gilmer") %>%
ggplot(aes(x = ns, y = values)) +
  geom_boxplot() +
  facet_wrap(~ res) +
  xlab("neighborhood size (meters)") +
  ylab("slope gradient (%)") + ylim(0, 100) + labs(caption = "y-axis max set at 100") +
  ggtitle("Gilmer")

filter(lidar, var == "slope" & loc == "Jefferson") %>%
  ggplot(aes(x = ns, y = values)) +
  geom_boxplot() +
  facet_wrap(~ res) +
  xlab("neighborhood size (meters)") +
  ylab("slope gradient (%)") + ylim(0, 20) + labs(caption = "y-axis max set at 20") +
  ggtitle("Jefferson")

# cupro boxplots
filter(lidar, var == "cupro" & loc == "Gilmer") %>%
  ggplot(aes(x = ns, y = values)) +
  geom_boxplot() +
  facet_wrap(~ res) +
  xlab("neighborhood size (meters)") +
  ylab("profile curvature (radians)") + ylim(-20, 20) + labs(caption = "y-axis min and max set at 20") +
  ggtitle("Gilmer")

filter(lidar, var == "cupro" & loc == "Jefferson") %>%
  ggplot(aes(x = ns, y = values)) +
  geom_boxplot() +
  facet_wrap(~ res) +
  xlab("neighborhood size (meters)") +
  ylab("profile curvature (radians)") + ylim(-20, 20) + labs(caption = "y-axis min and max set at 20") +
  ggtitle("Jefferson")


# cutan boxplots
filter(lidar, var == "cupro" & loc == "Gilmer") %>%
  ggplot(aes(x = ns, y = values)) +
  geom_boxplot() +
  facet_wrap(~ res) +
  xlab("neighborhood size (meters)") +
  ylab("tangential curvature (radians)") + ylim(-20, 20) + labs(caption = "y-axis min and max set at 20") +
  ggtitle("Gilmer")

filter(lidar, var == "cutan" & loc == "Jefferson") %>%
  ggplot(aes(x = ns, y = values)) +
  geom_boxplot() +
  facet_wrap(~ res) +
  xlab("neighborhood size (meters)") +
  ylab("tanngential curvature (radians)") + ylim(-20, 20) + labs(caption = "y-axis min and max set at 20") +
  ggtitle("Jefferson")

```


## Compute LiDAR Comparisons

```{r comparsions}

load(file = "C:/workspace2/github/thesis_wvu/trunk/scale/lidar_data2.RData")

lidar <- within(lidar, {
  values = ifelse(var == "aspect",  abs(180 - values), values)
  var    = ifelse(var == "aspect", "northness", var)
  ind    = paste(loc, var, res, ns, sep = "_")
  ns     = as.character(ns)
  })


vars <- c("loc", "var", "res")
lidar_dif <- {
  split(lidar, lidar[vars]) ->.;
  lapply(., function(x) {
    us = data.frame(unstack(x, values ~ ns))
    names(us) = sub("X", "", names(us))
    idx = !is.na(as.numeric(names(us)))
    na  = sort(as.numeric(names(us)[idx]))
    us  = us[as.character(na)]

    x2 = data.frame(
      x[1, vars],
      us,
      check.names      = FALSE,
      stringsAsFactors = FALSE
      )
    
    idx = which(!is.na(as.numeric(names(x2))))
    x3 = data.frame(
      x[1, vars],
      ns   = as.numeric(names(x2)[idx]),
      MD   = round(     colMeans( x2[, idx[1]] - x2[idx],    na.rm = TRUE), 3),
      RMSD = round(sqrt(colMeans((x2[, idx[1]] - x2[idx])^2, na.rm = TRUE)), 3),
      r    = round(           cor(x2[idx[1]],  x2[idx],      use = "pairwise.complete.obs"), 3)[1, ]
      )
  }) ->.;
  do.call("rbind", .)
  }

vars <- c("MD","RMSD", "r")
lidar_lo <- reshape(lidar_dif, 
                    direction = "long",
                    timevar = "variable", times = vars,
                    v.names = "value",    varying = vars
                    )
```


## Create Line Plots

```{r lines}

# slope Gradient
filter(lidar_lo, var == "slope" & variable %in% c("MD", "RMSD")) %>%
  ggplot(aes(x = ns, y = value, col = res)) +
  geom_line(lwd = 1) +
  geom_point(size = 2) +
  facet_wrap(~ variable + loc) +
  scale_color_discrete(name="grid size\n(meters)") +
  xlab("neighborhood size (meters)") +
  ylab("difference (%)") + 
  ggtitle("Slope Gradient")

# northness difference
filter(lidar_lo, var == "northness" & variable %in% c("MD", "RMSD")) %>%
  ggplot(aes(x = ns, y = value, col = res)) +
  geom_line(lwd = 1) +
  geom_point(size = 2) +
  facet_wrap(~ variable + loc) +
  scale_color_discrete(name="grid size\n(meters)") +
  xlab("neighborhood size (meters)") +
  ylab("differenct (degrees)") + 
  ggtitle("Northness")

# cupro difference
filter(lidar_lo, var == "cupro" & variable %in% c("MD", "RMSD")) %>%
  ggplot(aes(x = ns, y = value, col = res)) +
  geom_line(lwd = 1) +
  geom_point(size = 2) +
  facet_wrap(~ variable + loc) +
  scale_color_discrete(name="grid size\n(meters)") +
  xlab("neighborhood size (meters)") +
  ylab("difference (radians)") + 
  ggtitle("Profile Curvature")

# cutan difference
filter(lidar_lo, var == "cutan" & variable %in% c("MD", "RMSD")) %>%
  ggplot(aes(x = ns, y = value, col = res)) +
  geom_line(lwd = 1) +
  geom_point(size = 2) +
  facet_wrap(~ variable + loc) +
  scale_color_discrete(name="grid size\n(meters)") +
  xlab("neighborhood size (meters)") +
  ylab("difference (radians)") + 
  ggtitle("Tangential Curvature")

```

```{r correlations, fig.width=8, fig.height=10}

# correlations
filter(lidar_lo, variable %in% "r") %>%
  ggplot(aes(x = ns, y = value, col = res)) +
  geom_line(lwd = 1) +
  geom_point(size = 2) +
  facet_wrap(~ var + loc, ncol = 2) +
  theme(aspect.ratio = 1/2) +
  scale_color_discrete(name="grid size\n(meters)") +
  xlab("neighborhood size (meters)") +
  ylab("correlation coefficient (r)") + ylim(0, 1) + 
  ggtitle("Correlations")

```


# Case Study 2 - Soil and LSP correlations response to neighborhood size

## Tidy Soil Data

```{r soildata}

library(aqp)
library(dplyr)

fp <- "C:/Users/Stephen.Roecker/NextCloud/projects/thesis_wvu"

s <- read.csv(file.path(fp, "siteAttributes.csv"), stringsAsFactors = FALSE)
s[1:4] <- lapply(s[1:4], as.numeric)

h <- read.csv(file.path(fp, "horizonAttributes.csv"), stringsAsFactors = FALSE)
h$CaMg <- with(h, Ca + Mg) 
spc <- h
depths(spc) <- upedonid ~ hzdept + hzdepb

h_s <- aqp::slice(spc, 0:150 ~ fragvol + clay + sand + C + pH + CaMg, just.the.data = TRUE)
h_s$dep_int <- cut(h_s$hzdepb,
                   breaks = c(0, 15, 60, 100, 150), 
                   labels = c("0-15", "15-60", "60-100", "100-150")
                   )

h_di <- group_by(h_s, upedonid, dep_int) %>%
  summarize(fragvol = mean(fragvol, na.rm = TRUE),
            clay    = mean(clay,    na.rm = TRUE),
            C       = sum(C),
            pH      = mean(pH,      na.rm = TRUE),
            CaMg    = sum(CaMg), 
            hzthk   = sum(!is.na(.pctMissing))
            )%>%
  mutate(fragvol = ifelse(fragvol <= 0.1, 0.1, fragvol),
          C       = ifelse(C == 0,         NA,  C),
          CaMg    = ifelse(CaMg == 0,      NA,  CaMg)
          )
sh_di <- merge(s, h_di, by = "upedonid", all.x = TRUE)

```

## Depth Plots

```{r explore}

library(ggplot2)
library(GGally)

# Depth Plot

h_slab <- slab(spc, ~ fragvol + clay + C + pH + CaMg)

ggplot(h_slab, aes(x = bottom, y = p.q50)) +
  geom_line() +
  geom_ribbon(aes(ymin = p.q5,  ymax = p.q95, x = bottom), alpha = 0.2) + 
  geom_ribbon(aes(ymin = p.q25, ymax = p.q75, x = bottom), alpha = 0.2) + 
  xlim(150, 0) +
  facet_wrap(~ variable, scales = "free_x") +
  coord_flip() +
  xlab("depth (cm)") +
  ylab("5th, 25th, Median, 75th, and 95th Quantiles") +
  ggtitle("Depth Plot of Soil Properties")


# Scatter Plot Matrix

h$CaMg_log <- log(h$CaMg + 0.1)
sh_di$CaMg_log <- log(sh_di$CaMg + 0.1)

vars <- c("fragvol", "clay", "C", "pH", "CaMg_log")
ggpairs(h[vars])
ggpairs(sh_di[vars])

```


## Sample Geodata and Correlate with Soil Depth Intervals

```{r geodata, eval = FALSE}

library(sp)
library(sf)
library(raster)

pts <- sh_di
coordinates(pts) <- ~ utm_easting + utm_northing
proj4string(pts) <- CRS("+init=epsg:26917")

pts2 <- st_sf(sh_di, 
              geometry = st_sfc(st_multipoint(as.matrix(sh_di[3:4]))),
              crs      = "+init=epsg:26917"
              )

# stack SAGA rasters

load(file = "C:/workspace2/github/thesis_wvu/trunk/scale/geodata_df.RData")

sg <- {
  subset(geodata, ! var %in% c("elev", "cucon") & ! grepl("slopeR|slopeD", var) & ! ws %in% c(27, 45, 63, 81)) ->.;
  split(., .$res) ->.;
  lapply(., function(x) { 
    cat("raster stacking and extracting, correlating, stacking, and tidying", x$res[1], "\n")
    rs = stack(x$sdat)
    sg = as.data.frame(raster::extract(rs, pts, sp = TRUE))
    }) ->.;
  }

sg2 <- {
  lapply(sg, function(x) {
    # split by depth interval
    split(x, x$dep_int) ->.;
    # compute correlation and convert to long format
    lapply(., function(x2) {
      test = stack(data.frame(
        fragvol = cor(x2$fragvol, x2[16:ncol(x2)], use = "pairwise.complete.obs"),
        clay    = cor(x2$clay,    x2[16:ncol(x2)], use = "pairwise.complete.obs"),
        C       = cor(x2$C,       x2[16:ncol(x2)], use = "pairwise.complete.obs"),
        pH      = cor(x2$pH,      x2[16:ncol(x2)], use = "pairwise.complete.obs"),
        CaMg    = cor(x2$CaMg,    x2[16:ncol(x2)], use = "pairwise.complete.obs")
        ))
      test$ind = as.character(test$ind)
      test$dep_int = x2$dep_int[1]
      return(test)
      }) -> .;
    do.call("rbind", .) ->test;
    
    # split property.filename grouping variable into separate columns
    test = cbind(
      test,
      data.frame(
        do.call("rbind",
                strsplit(test$ind, "\\.|_")
                ),
        stringsAsFactors = FALSE
        )
      )
    names(test)[4:7] = c("prop", "source", "area", "var")
    
    # split source and variable columns into additional columns
    test = within(test, {
      res    = substr(source, 5, 8)
      res    = as.numeric(substr(res, 1, nchar(res) - 1))
      source = substr(source, 1, 4)
      ws     = sub("slope|aspect|cupro|cutan", "", var)
      ws     = as.numeric(substr(ws, 1, nchar(ws) - 1))
      ns     = ws * res
      var[grepl("slope",  var)] = "slope"
      var[grepl("aspect", var)] = "aspect"
      var[grepl("cupro",  var)] = "cupro"
      var[grepl("cutan",  var)] = "cutan"
    })

    }) ->.;
  do.call("rbind", .) ->.;
  }

save(sg2, file = "C:/Users/Stephen.Roecker/NextCloud/projects/thesis_wvu/soil_correlations.RData")

```

## Create Line Plots

```{r correlations2, fig.dim = c(8, 10)}

load(file = "C:/Users/Stephen.Roecker/NextCloud/projects/thesis_wvu/soil_correlations.RData")

# 3-meter DEM and Increasing Window Sizes
filter(sg2, res == 3) %>%
  ggplot(aes(x = ns, y = values, col = var)) +
  geom_line(lwd = 1) +
  geom_hline(yintercept = 0) +
  geom_point(size = 2) +
  facet_wrap(~ prop + dep_int, ncol = 4) +
  theme(aspect.ratio = 1) +
  xlab("neighborhood size (meters)") +
  ylab("correlation coefficient (r)") +
  ggtitle("3-meter DEM")

# 9-meter DEM and Increasing Window Sizes
filter(sg2, res == 9) %>%
  ggplot(aes(x = ns, y = values, col = var)) +
  geom_line(lwd = 1) +
  geom_hline(yintercept = 0) +
  geom_point(size = 2) +
  facet_wrap(~ prop + dep_int, ncol = 4) +
  theme(aspect.ratio = 1) +
  xlab("neighborhood size (meters)") +
  ylab("correlation coefficient (r)") +
  ggtitle("9-meter DEM")

# 27-meter DEM and Increasing Window Sizes
filter(sg2, res == 27) %>%
  ggplot(aes(x = ns, y = values, col = var)) +
  geom_line(lwd = 1) +
  geom_hline(yintercept = 0) +
  geom_point(size = 2) +
  facet_wrap(~ prop + dep_int, ncol = 4) +
  theme(aspect.ratio = 1) +
  xlab("neighborhood size (meters)") +
  ylab("correlation coefficient (r)") +
  ggtitle("27-meter DEM")

# All DEMs and 3x3 Window Size
filter(sg2, ws == 3) %>%
  ggplot(aes(x = res, y = values, col = var)) +
  geom_line(lwd = 1) +
  geom_hline(yintercept = 0) +
  geom_point(size = 2) +
  facet_wrap(~ prop + dep_int, ncol = 4) +
  theme(aspect.ratio = 1) +
  xlab("neighborhood size (meters)") +
  ylab("correlation coefficient (r)") +
  ggtitle("All DEMs and 3x3 Window Size")
```
